services:
  api:
    build:
      context: .
      dockerfile: deploy/Dockerfile.multi
      target: api
    image: bookstore-api
    ports:
      - "8888:8888"
    depends_on:
      - add
      - check

  add:
    build:
      context: .
      dockerfile: deploy/Dockerfile.multi
      target: add
    image: bookstore-add
    ports:
      - "8081:8081"

  check:
    build:
      context: .
      dockerfile: deploy/Dockerfile.multi
      target: check
    image: bookstore-check
    ports:
      - "8082:8082"
